version: '3.8'

services:
  api:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_APP=api.py
      - FLASK_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped 